# Generated by Django 6.0 on 2026-01-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Productos.carrito'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.productvariant'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='optiontype',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_types', to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Productos.optiontype'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Productos.categoria'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Productos.producto'),
        ),
    ]
